package:
    name: opensim
    version: "4.2"

source:
#    path: /home/kidzik/workspace/opensim-core
    git_url: https://github.com/opensim-org/opensim-core.git
    git_rev: "dbde45530883b4755f2933a9aa1231975313dd3c"
  
build:
    number: 12
    # NOTE : For C++11 builds, vc16/VS 2019 are the only acceptable targets
    features:
        - vc16                # [win and py35]
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true

requirements:
  run:
        - python
        - numpy
        # - openblas
        - freeglut
  build:
        - swig
        - toolchain
        - cmake >=3.15
        - numpy >=1.19
        # - python                  # [win]

about:
    home: http://opensim.stanford.edu
    license: Apache-2.0
    summary: >
        OpenSim is software that lets users develop models of musculoskeletal
        structures and create dynamic simulations of movement.

extra:
    recipe-maintainers:
        - aymanhab
        - kidzik
